---
# Template configuration files for subscription-manager

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"
  loop: "{{ subscription-manager_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - subscription-manager_enable_selinux
  become: true
